### ISSUE TITLE
Goroutine issues 

### ISSUE THREAD

**Issue by kc1116** [lann/builder#8]
Hey I am using builder in a few different spots in my application as well as in multiple different goroutines. Is this package thread safe? I see that the registry.go map always panics about concurrent map writes

**Comment by lann** [comment]
The registry code is definitely *not* goroutine-safe (as you see). The builders themselves are immutable and so should be intrinsically goroutine-safe, but I highly recommend building and testing with `-race` during development if you are ever unsure.

**Comment by kc1116** [comment]
Thanks for the reply, I actually want to make a pull request that's working well for me in a multithreaded environment using the new Go 1.9 sync.map
